**Numpy** 모듈에서 제공하는 배열의 기능  
1-1. zeros() : 괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화  
1-2. ones() : 괄호 안에 입력된 숫자만큼의 원소를 생성하고 1로 초기화

In [3]:
import numpy as np
x = np.zeros([4])
y = np.zeros([2, 4])
z = np.zeros([3, 2, 4])
# print(x)
print(y)
# print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

2. mean : 평균 구하기

In [121]:
# 파이썬 리스트로 실행
x = [1,3,5]
x.mean()

AttributeError: 'list' object has no attribute 'mean'

In [136]:
# numpy 모듈 np라는 이름으로 불러오기
import numpy as np

# 리스트를 numpy 형식으로 변환, numpy 배열 만들기
x=np.array([1,3,5])

# 출력
print(x.mean())
print(x.shape)

3.0
(3,)


In [131]:
# 2차원 배열
a = np.array([[1,2,3],[2,3,4],[3,4,5]])
# 출력 결과
print(a.shape)

(3, 3)


알고가자!  
mean() 은 numpy 모듈이 제공하는 함수  
shape 는 numpy 배열 객체의 속성

In [134]:
# class 객체의 함수와 속성 예시
class Person:
    bag = []
 
    def put_bag(self, stuff):
        self.bag.append(stuff)
 
james = Person()
james.put_bag('책')
 
# maria = Person()
# maria.put_bag('열쇠')
 
print(james.bag)
# print(maria.bag)

['책']


In [138]:
# 반드시 리스트 형태로 입력해야한다.
# x=np.array(1,3,5)
x=np.array([1,3,5])
print(x)

[1 3 5]


3. reshape : shape 바꾸기

In [141]:
# x = np.array([1,3,5,7,9,11]).reshape(3,2)
x = np.array([1,3,5,7,9,11])
x = x.reshape(3,2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [145]:
x=np.array([[1,3,5],[2,4,6]])
print(x[1])
print(x[1].mean())
print(x.mean())
print(x.shape)

[2 4 6]
4.0
3.5
(2, 3)


In [146]:
# 출력 결과
x=[[1,11],[2,12],[2,12],[3,13]]
print(x[1][1])

12


Numpy 배열의 **슬라이싱**

In [151]:
# 파이썬 리스트에서, 각 원소인 1차원 배열의 2번째 요소만 출력하기
# 목표 : 11, 12, 13
x=[[1,11],[2,12],[3,13]]
# print(x[:,1])
print(x[:][1])

[2, 12]


In [7]:
# numpy 슬라이싱
import numpy as np
x = np.array([[1,11],[2,12],[3,13]])
print(x[:,1])
print(x[:][1])

[11 12 13]
[ 2 12]


In [ ]:
import numpy as np
x = [[1,11],[2,12],[3,13]]
print(np.array(x[:,1]))

In [155]:
# 다른 방식
import numpy as np
x = np.array([[1,11],[2,12],[3,13]])
print(x[:,1])

[11 12 13]


In [160]:
# 출력 결과
import numpy as np
x = [[1,11],[2,12],[3,13]]
print(np.array(x[:][0]))

[ 1 11]


numpy 연산

In [170]:
# 파이썬에서 제공하는 sqrt함수
import math
math.sqrt(2)

# num=[2,3,4]
# result = list(map(math.sqrt, num))
# print(result)

# result=[]
# for i in num:
#     result.append(math.sqrt(i))
# print(result)

[1.4142135623730951, 1.7320508075688772, 2.0]


In [162]:
math.sqrt([2,3,4])

TypeError: must be real number, not list

In [171]:
import numpy as np
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [173]:
import numpy as np
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [174]:
x=x.reshape(3,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [175]:
# 위의 x에서 6을 출력하려면?
# 정답
print(x[1][1])

6


제로벡터와 제로행렬

In [177]:
import numpy as np
zero_vector=np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [180]:
# zero_vector=np.zeros([4,3])
zero_vector=np.zeros((4,3))
print(zero_vector)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [183]:
import numpy as np
my_array=np.zeros(15).reshape(3,5)
my_array+=4
print(my_array)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


In [187]:
import numpy as np
my_array=np.ones(15).reshape(3,5)
my_array/=2
print(my_array)

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]


#### 전치행렬 개념 알고가기  
전치행렬(Transpose Matrix)은 행과 열을 교환하여 얻어지는 행렬을 말한다.  
주대각선을 기준으로 위치를 바꾼다.

In [188]:
x=[[1,2],[3,4]]
print(x.transpose())

AttributeError: 'list' object has no attribute 'transpose'

In [194]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6]])
print(x.transpose())

[[1 3 5]
 [2 4 6]]


In [190]:
# 출력 결과
x=[1,2,3]
y=[4,5,6]
z = x + y
print(z)

[1, 2, 3, 4, 5, 6]


In [193]:
# 출력 결과
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[5 7 9]


In [195]:
# 곱셈
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
print(z)

[ 4 10 18]


In [196]:
# 빈칸
import numpy as np
x = np.array([4,8,10])
y = np.array([2,4,5])
z = x/y
print(z)
# 목표 [2. 2. 2.]

[2. 2. 2.]


In [197]:
# 복습 짚고 넘어가기
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:,1])

[4 5 6]
[2 5 8]


In [198]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,1]+y[:,1])

[ 5 11 17]


#### 리스트 인덱싱

In [199]:
a=np.array([10,20,30,40,50,60,70])
i=[1,3,5]
print(a[i])

[20 40 60]


In [209]:
# 출력 결과
import numpy as np
a=np.array([10,20,30,40,50,60,70])
b=a[1:6:2] # 슬라이싱
print('b:', b)
b[1]=10
print('b:', b)
print('a:', a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 10 50 60 70]


In [210]:
# 출력 결과
import numpy as np
a=np.array([10,20,30,40,50,60,70])
b=np.array(a[1:6:2]) # 슬라이싱
print('b:', b)
b[1]=10
print('b:', b)
print('a:', a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


#### 불리언(Boolean)

In [211]:
a=np.array([10,20,30,40,50,60,70])
b=a>50
print(b)

[False False False False False  True  True]


In [215]:
a = np.random.random(5)
print(a)

[0.00564016 0.04251929 0.17703949 0.7662739  0.94392852]


In [217]:
print(np.all(a>=0.7))
# print(np.any(a>0.7))

False


In [218]:
height=np.array([173,168,171,189,179])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = (weight/(height**2))*10000
print(bmi)
#사람들의 bmi를 하나의 리스트로 출력하세요

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [219]:
#bmi 값이 21보다 크면 True, 그렇지 않으면 false를 출력하세요
print(bmi>21)

[ True False  True  True  True]


#### 같은 간격 나누기  
(1) linespace()  
(2) logspace()

In [221]:
print(np.linspace(0,12,4))

[ 0.  4.  8. 12.]


In [222]:
print(np.linspace(0,12,4,retstep=True)) # 간격을 마지막에 출력한다

(array([ 0.,  4.,  8., 12.]), 4.0)


In [223]:
print(np.linspace(0,12,4,endpoint=False))
# 간격의 시작 값만 출력하고, 마지막 값 출력하지 않는다.
# default 는 true

[0. 3. 6. 9.]


In [224]:
# 참고
np.logspace(1,2,5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])